---
abstract: "allow your class's DOES method to respond the affirmative to delegated roles"
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Test::More: '0.61'
configure_requires:
  ExtUtils::MakeMaker: '6.17'
dynamic_config: 0
generated_by: 'Moose::Meta::Class::__ANON__::SERIAL::8 version , CPAN::Meta::Converter version 2.140640'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MooseX-Does-Delegated
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  MooseX::Does::Delegated:
    file: lib/MooseX/Does/Delegated.pm
    version: '0.004'
requires:
  Moose::Role: '0'
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/MooseX-Does-Delegated/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=MooseX-Does-Delegated
  homepage: https://metacpan.org/release/MooseX-Does-Delegated
  license: http://dev.perl.org/licenses/
  repository: git://github.com/tobyink/p5-moosex-does-delegated.git
version: '0.004'
