---
abstract: "allow your class's DOES method to respond the affirmative to delegated roles"
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: MooseX::Does::Delegated
name: MooseX-Does-Delegated
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Moose::Role: 0
  perl: 5.8.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=MooseX-Does-Delegated
  homepage: https://metacpan.org/release/MooseX-Does-Delegated
  license: http://dev.perl.org/licenses/
  repository: https://bitbucket.org/tobyink/p5-moosex-does-delegated
version: 0.003
